### ISSUE TITLE
Update your documentations!

### ISSUE THREAD

**Issue by mehdiMj-ir** [arvancloud/terraform-provider-arvan#19]
I tried to use Terraform on Arvan and it failed every time.

## Reproduce the error:

1. I copy and paste your default code
2. Try `terraform init`
3. Change the **ApiKey**
4. Try `terraform plan` (*it works*)
5. Try `terraform apply` (*hit yes*)
# error
![Screenshot_20230125_152051](https://user-images.githubusercontent.com/20270329/214558355-12033349-a96c-4194-949a-70c92ac5ca88.png)

**Comment by hatamiarash7** [comment]
This problem was related to the old version ( `0.6.1` ). Use version `0.6.4`. Also, the default version in the documentation and examples was updated.

**Comment by mehdiMj-ir** [comment]
Thanks for your respond, this was a simple copy and paste from [README.md](https://github.com/arvancloud/terraform-provider-arvan/blob/main/README.md) and I hoped that it will work by default (I was on `0.6.4` too).

Here is some screenshots and video of my terminal:

`terraform init`
![Screenshot_20230301_235157](https://user-images.githubusercontent.com/20270329/222264513-f4f2bdc4-b30f-4186-b9d1-79dd2d16b24c.png)
`terraform apply`
![Screenshot_20230301_235223](https://user-images.githubusercontent.com/20270329/222264532-dda9e7ba-9854-4285-9020-fede1d50a22f.png)

This captured video of my terminal and my `main.tf` file:
[Terminal](https://asciinema.org/a/RwRz8jKFbdfgxdTSOQsbwWvBH)

```hcl
# main.tf
terraform {
  required_providers {
    arvan = {
      source  = "arvancloud/arvan"
      version = "0.6.4" # put the version here
    }
  }
}

variable "ApiKey" {
  type = string
  default = "x-y-z"
  sensitive = true
}

provider "arvan" {
  api_key = var.ApiKey
}

variable "abrak-name" {
  type = string
  default = "terraform-abrak-example"
}

variable "region" {
  type = string
  default = "ir-thr-c2" # Forogh Datacenter
}

resource "arvan_iaas_abrak" "abrak-1" {
  region = var.region
  flavor = "g1-1-1-0"
  name   = var.abrak-name
  image {
    type = "distributions"
    name = "debian/11"
  }
  disk_size = 25
}

data "arvan_iaas_abrak" "get_abrak_id" {
  depends_on = [
    arvan_iaas_abrak.abrak-1
  ]

  region = var.region
  name   = var.abrak-name
}

output "details-abrak-1" {
  value = data.arvan_iaas_abrak.get_abrak_id
}
```
I already told them to update their documentation, This used to be `Arvan` not some random provider, It's sad.
![](https://user-images.githubusercontent.com/20270329/222266036-e599aa3b-5353-4338-aa80-9cc4bbabb0bf.png)

**Comment by hatamiarash7** [comment]
Please check your `ApiKey` variable again. Make sure it is structured like this: `Apikey <UUID>`. For example:

```tf
variable "ApiKey" {
  type = string
  default = "Apikey 3205793c-1d56-26dc-ab25-81425aa46f60"
  sensitive = true
}
```

**Comment by mehdiMj-ir** [comment]
Thank you very much for your time and effort.
They need to update their **documentations** and put some **tutorials** for us.
